# **TOPIK MODELING**

Topik modeling biasanya digunakan untuk mengelompokkan data berdasarkan topik yang telah ditentukan

Data : Komentar dengan kata kunci "capres22024"

Tugas : LSA : TF IDF & Singuler Value Decomposition (SVD)

Output:

-> Kontribusi dokumen terhadap topik

-> Kontribusi term terhadap topik

In [2]:
import pandas as pd
from googleapiclient.discovery import build

In [3]:
def video_comments(video_id):
	# empty list for storing reply
	replies = []

	# creating youtube resource object
	youtube = build('youtube', 'v3', developerKey=api_key)

	# retrieve youtube video results
	video_response = youtube.commentThreads().list(part='snippet,replies', videoId=video_id).execute()

	# iterate video response
	while video_response:
		
		# extracting required info
		# from each result object
		for item in video_response['items']:
			
			# Extracting comments ()
			published = item['snippet']['topLevelComment']['snippet']['publishedAt']
			user = item['snippet']['topLevelComment']['snippet']['authorDisplayName']

			# Extracting comments
			comment = item['snippet']['topLevelComment']['snippet']['textDisplay']
			likeCount = item['snippet']['topLevelComment']['snippet']['likeCount']

			replies.append([published, user, comment, likeCount])
			
			# counting number of reply of comment
			replycount = item['snippet']['totalReplyCount']

			# if reply is there
			if replycount>0:
				# iterate through all reply
				for reply in item['replies']['comments']:
					
					# Extract reply
					published = reply['snippet']['publishedAt']
					user = reply['snippet']['authorDisplayName']
					repl = reply['snippet']['textDisplay']
					likeCount = reply['snippet']['likeCount']
					
					# Store reply is list
					#replies.append(reply)
					replies.append([published, user, repl, likeCount])

			# print comment with list of reply
			#print(comment, replies, end = '\n\n')

			# empty reply list
			#replies = []

		# Again repeat
		if 'nextPageToken' in video_response:
			video_response = youtube.commentThreads().list(
					part = 'snippet,replies',
					pageToken = video_response['nextPageToken'], 
					videoId = video_id
				).execute()
		else:
			break
	#endwhile
	return replies

In [4]:
api_key = 'AIzaSyD6Lb7fJBcMcxcvKsIRctUXv_bwTyxc56w' 
# url = https://www.youtube.com/watch?v=zKtSitv-VdQ
video_id = "zKtSitv-VdQ" #id video
# Call function
comments = video_comments(video_id)
comments

[['2023-05-09T10:50:36Z',
  'Sugeng',
  'Halah, ilmunya pak beye di pakai, memposisikan diri sebagai orang yang teraniaya, terzolimi ? Nis nis agak cerdas dikit lah dalam mencari simpati publik',
  0],
 ['2023-05-09T07:43:32Z',
  'Sarwo Rahayu',
  'Harusnya jokowi lanjut tapi karna iuu membatasi jadi ganjar solusinya',
  0],
 ['2023-05-09T07:39:53Z', 'Sarwo Rahayu', 'Anis nol', 0],
 ['2023-05-09T03:08:52Z',
  'bakayaro_16',
  'Knapa nis lo takut kalah krna gk di dukung pak jokowi ??<br>Gw gk mau negara ini jatuh ke tangan aseng kyk lo',
  0],
 ['2023-05-08T19:29:40Z',
  'TaliBAN & TaliDRUN sebelas dua belas',
  '😂😂😂😂😂 ngakak😂😂😂😂😂 ...kmi rakyt tdk pernah di intervensi, oleh negara/pemerinth slama sdh brapa kali gnti presiden,.<br>Kok anda tiba2 ngong kek gitu😅😅😅😅',
  0],
 ['2023-05-08T19:02:58Z',
  'Bahari Mania',
  'Menurut saya sih gak ada intervensi, lebay deh',
  1],
 ['2023-05-08T17:34:46Z',
  'wisang Geni',
  '😂😂😂😂😂 rakyat  sudah tahu mana .. bagus jadi  RI1.. anis mana bisa... ja

In [5]:
df = pd.DataFrame(comments, columns=['publishedAt', 'authorDisplayName', 'textDisplay', 'likeCount'])
df

publishedAt                     authorDisplayName  \
0   2023-05-09T10:50:36Z                                Sugeng   
1   2023-05-09T07:43:32Z                          Sarwo Rahayu   
2   2023-05-09T07:39:53Z                          Sarwo Rahayu   
3   2023-05-09T03:08:52Z                           bakayaro_16   
4   2023-05-08T19:29:40Z  TaliBAN & TaliDRUN sebelas dua belas   
5   2023-05-08T19:02:58Z                          Bahari Mania   
6   2023-05-08T17:34:46Z                           wisang Geni   
7   2023-05-08T16:34:46Z                          Zalfa Syafiq   
8   2023-05-08T15:23:57Z                          Ethan Negara   
9   2023-05-08T14:39:56Z                            Abie Arman   
10  2023-05-08T13:25:56Z                      Selamat Manurung   
11  2023-05-08T10:10:47Z                          Tepz Channel   
12  2023-05-08T09:58:47Z                       Muhammad Mansur   
13  2023-05-08T09:32:38Z                     wireBackty Azhary   
14  2023-05-08T09:25:30Z                           Adul Rahman   
15  2023-05-08T09:12:34Z                            raffa azka   
16  2023-05-08T09:08:37Z                         ngadiman ayah   
17  2023-05-08T09:06:43Z                         ngadiman ayah   
18  2023-05-08T09:05:57Z                         ngadiman ayah   
19  2023-05-08T09:04:33Z                         yoga prasetya   
20  2023-05-08T08:48:45Z                         Putri Mprapen   
21  2023-05-08T08:48:44Z                                Gi Joe   
22  2023-05-08T08:46:43Z                           Dana Kusuma   
23  2023-05-08T15:32:18Z             Salunga Institute Channel   
24  2023-05-08T08:29:37Z                             Soe Kardi   
25  2023-05-08T08:27:43Z                             Nur Ahmad   
26  2023-05-08T08:19:07Z                          RUMAH SERVIS   
27  2023-05-08T08:17:40Z                       Harizon Yusiana   
28  2023-05-08T08:05:46Z                             Agung Oka   
29  2023-05-08T08:03:41Z                         Ega Adi Putra   
30  2023-05-08T07:58:41Z                     Koes Wahyuningsih   
31  2023-05-08T07:55:22Z                            nela zahra   
32  2023-05-08T07:55:12Z                           Ardian Syah   
33  2023-05-08T07:49:41Z                       Alfitri Afrizal   
34  2023-05-08T07:49:29Z                       Rngt Setyawulan   
35  2023-05-08T07:48:55Z                           Queen Queen   
36  2023-05-08T07:47:43Z                       ferry hariyanto   
37  2023-05-08T07:47:23Z                          Ny Muchnizar   
38  2023-05-08T07:47:18Z                          shasa flower   
39  2023-05-08T14:38:24Z                         Alvin Affandi   
40  2023-05-08T07:42:39Z               anggi,  rafael dan reza   
41  2023-05-08T14:36:55Z                         Alvin Affandi   
42  2023-05-08T07:42:26Z                              ilham gg   
43  2023-05-08T07:42:24Z                                Tumino   
44  2023-05-08T07:40:15Z                          euis rufaida   
45  2023-05-08T07:47:27Z                   Sohibandi Sohibandi   
46  2023-05-08T07:39:45Z                         Hidayat Yusuf   
47  2023-05-08T07:37:41Z                                erlana   
48  2023-05-08T07:36:12Z                                  YonQ   
49  2023-05-08T07:36:07Z                       Nono Sudarmanto   
50  2023-05-08T07:35:14Z                             Bening S.   
51  2023-05-08T07:35:04Z                                  YonQ   
52  2023-05-08T07:33:59Z                             ziva acna   

                                          textDisplay  likeCount  
0   Halah, ilmunya pak beye di pakai, memposisikan...          0  
1   Harusnya jokowi lanjut tapi karna iuu membatas...          0  
2                                            Anis nol          0  
3   Knapa nis lo takut kalah krna gk di dukung pak...          0  
4   😂😂😂😂😂 ngakak😂😂😂😂😂 ...kmi rakyt tdk pernah di i...          0  
5      Menurut saya sih gak ada intervensi, le

In [6]:
df.to_csv("capres2024.csv",index=False)

Tahapan preprocessing

- Cleaninng text

- Lowercase

- Slank word

- Tokenizing

- Stopword

- Stemming

In [7]:
!pip install Sastrawi

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 4.8 MB/s eta 0:00:00


In [8]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
import re
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.tokenize import sent_tokenize, word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [9]:
dt = pd.read_csv("/content/drive/MyDrive/prosaindata/tugas/capres2024.csv")
dt

publishedAt                     authorDisplayName  \
0   2023-05-09T10:50:36Z                                Sugeng   
1   2023-05-09T07:43:32Z                          Sarwo Rahayu   
2   2023-05-09T07:39:53Z                          Sarwo Rahayu   
3   2023-05-09T03:08:52Z                           bakayaro_16   
4   2023-05-08T19:29:40Z  TaliBAN & TaliDRUN sebelas dua belas   
5   2023-05-08T19:02:58Z                          Bahari Mania   
6   2023-05-08T17:34:46Z                           wisang Geni   
7   2023-05-08T16:34:46Z                          Zalfa Syafiq   
8   2023-05-08T15:23:57Z                          Ethan Negara   
9   2023-05-08T14:39:56Z                            Abie Arman   
10  2023-05-08T13:25:56Z                      Selamat Manurung   
11  2023-05-08T10:10:47Z                          Tepz Channel   
12  2023-05-08T09:58:47Z                       Muhammad Mansur   
13  2023-05-08T09:32:38Z                     wireBackty Azhary   
14  2023-05-08T09:25:30Z                           Adul Rahman   
15  2023-05-08T09:12:34Z                            raffa azka   
16  2023-05-08T09:08:37Z                         ngadiman ayah   
17  2023-05-08T09:06:43Z                         ngadiman ayah   
18  2023-05-08T09:05:57Z                         ngadiman ayah   
19  2023-05-08T09:04:33Z                         yoga prasetya   
20  2023-05-08T08:48:45Z                         Putri Mprapen   
21  2023-05-08T08:48:44Z                                Gi Joe   
22  2023-05-08T08:46:43Z                           Dana Kusuma   
23  2023-05-08T15:32:18Z             Salunga Institute Channel   
24  2023-05-08T08:29:37Z                             Soe Kardi   
25  2023-05-08T08:27:43Z                             Nur Ahmad   
26  2023-05-08T08:19:07Z                          RUMAH SERVIS   
27  2023-05-08T08:17:40Z                       Harizon Yusiana   
28  2023-05-08T08:05:46Z                             Agung Oka   
29  2023-05-08T08:03:41Z                         Ega Adi Putra   
30  2023-05-08T07:58:41Z                     Koes Wahyuningsih   
31  2023-05-08T07:55:22Z                            nela zahra   
32  2023-05-08T07:55:12Z                           Ardian Syah   
33  2023-05-08T07:49:41Z                       Alfitri Afrizal   
34  2023-05-08T07:49:29Z                       Rngt Setyawulan   
35  2023-05-08T07:48:55Z                           Queen Queen   
36  2023-05-08T07:47:43Z                       ferry hariyanto   
37  2023-05-08T07:47:23Z                          Ny Muchnizar   
38  2023-05-08T07:47:18Z                          shasa flower   
39  2023-05-08T14:38:24Z                         Alvin Affandi   
40  2023-05-08T07:42:39Z               anggi,  rafael dan reza   
41  2023-05-08T14:36:55Z                         Alvin Affandi   
42  2023-05-08T07:42:26Z                              ilham gg   
43  2023-05-08T07:42:24Z                                Tumino   
44  2023-05-08T07:40:15Z                          euis rufaida   
45  2023-05-08T07:47:27Z                   Sohibandi Sohibandi   
46  2023-05-08T07:39:45Z                         Hidayat Yusuf   
47  2023-05-08T07:37:41Z                                erlana   
48  2023-05-08T07:36:12Z                                  YonQ   
49  2023-05-08T07:36:07Z                       Nono Sudarmanto   
50  2023-05-08T07:35:14Z                             Bening S.   
51  2023-05-08T07:35:04Z                                  YonQ   
52  2023-05-08T07:33:59Z                             ziva acna   

                                          textDisplay  likeCount  
0   Halah, ilmunya pak beye di pakai, memposisikan...          0  
1   Harusnya jokowi lanjut tapi karna iuu membatas...          0  
2                                            Anis nol          0  
3   Knapa nis lo takut kalah krna gk di dukung pak...          0  
4   😂😂😂😂😂 ngakak😂😂😂😂😂 ...kmi rakyt tdk pernah di i...          0  
5      Menurut saya sih gak ada intervensi, le

**Cleaning Text**

In [13]:
clean_tag = re.compile('@\S+')
clean_url = re.compile('https?:\/\/.*[\r\n]*')
clean_hastag = re.compile('#\S+')
clean_symbol = re.compile('[^a-zA-Z]')
def clean_punct(text):
    text = clean_tag.sub('', text)
    text = clean_url.sub('', text)
    text = clean_hastag.sub(' ', text)
    text = clean_symbol.sub(' ', text)
    return text
# Buat kolom tambahan untuk data description setelah dilakukan clean 
preproces= dt['textDisplay'].apply(clean_punct)
dt_clean=pd.DataFrame(preproces)
dt_clean

textDisplay
0   Halah  ilmunya pak beye di pakai  memposisikan...
1   Harusnya jokowi lanjut tapi karna iuu membatas...
2                                            Anis nol
3   Knapa nis lo takut kalah krna gk di dukung pak...
4         ngakak         kmi rakyt tdk pernah di i...
5      Menurut saya sih gak ada intervensi  lebay deh
6         rakyat  sudah tahu mana    bagus jadi  R...
7   jual gagasan saja jangan jual tuduhan  belar l...
8   saatnya orang keturunan yaman seperti pak anie...
9   anies boneka amrik  tak rela indonesia maju  m...
10  Saya tdk merasa diintervensi negara  Mau negar...
11  Anies mimpi jadi presiden indonesia   tapi leb...
12                                      Mulut mu Anis
13  Rakyat gk bodoh quot Amat   hd rakyat SDH tau ...
14            Betul omongan  pak anis tapi kerja omdo
15  Mendidik rakyat lebih penting bung  biar gk salah
16  Koar quot  presiden ikut cpur malah lebih baha...
17  Inilah ciri orang takut kalah udah di gebar ge...
18  Sejak dulu klompok PKS dan kadrun jejak digita...
19               Belom aja maju udah panik duluan wkw
20                                     Bnyk cebong   
21   Klo gk ikut campur di senayan wktu itu ngapain  
22  Rakyat sdh cerdas dn berdaulat unt memilih pem...
23  Saya Yakin Yg Nda Dukung Anis Baswedan Yang Ca...
24                 Tp bgmn kl negara mmbantu anis    
25  Bener pak Jokowi harusnya melihat pendahulunya...
26  Anies Baswedan ngomong apa sih kamu melecehkan...
27  Dasarnya munafik sudah terlihat kau bersikap s...
28  Ga perlu cari orang yg tdk cakap utk bekerja y...
29                           katakan tidak untuk anis
30                CUMA  MAKEKAR  CAPRES     MUKIDI   
31  Urus ssja ngara knaoa ikut cmpur btul rkyt pun...
32  Bohog terus kapan ya gk bohong  pada takut kal...
33  INGAT JAKARTA   THN TERAKHIR      br cukup jak...
34  Baguslah pintar berkata kata yg tujuannya baik...
35       Cocok jadi tukang jual jamu  Pinter ngomong 
36         Klo soal pidato kayak gini mah jagonya dia
37  Anid lucu siapa yg interpensi goblok  amat yg ...
38  ANIES UDAH JELAS  SURVEI NYA RENDAH KETAKUTAN ...
39      survey mana  cb cari survey di youtube    ...
40  Pada takut jokowi karena pengaruhnya besar pem...
41                                   Ke balik kali   
42         di intervensi mayatnya ga di sholatkan    
43  Inilah congor Anis yg slalu suudzon dengan sia...
44  Rakyat dah pinter klo yg ngerti dukung yg bena...
45  SIAPA YG INTERPENSI        GK ADA AKU  GK MILI...
46  KompasTV sdh condong ke Anies  alias tdk netra...
47  semogah pak Anis sehat selalu senantiasa dalam...
48  SEMPAK SI BEWOK SURUH JADI PRESIDEN     YANG B...
49  Iya rakyat dah mampu menilai mana yg cuma pand...
50                                         Wan NGIBUL
51  KETAKUTAN KALAH     BELUM AJA PEMILU UDAH KEOK...
52                  takut elektabilitas jokowi ya nis

**Lower Case**

In [14]:
def clean_lower(lwr):
    lwr = lwr.lower() # lowercase text
    return lwr
# Buat kolom tambahan untuk data description yang telah dicasefolding  
dt_clean = dt_clean['textDisplay'].apply(clean_lower)
dt_lowecase=pd.DataFrame(dt_clean)
dt_lowecase

textDisplay
0   halah  ilmunya pak beye di pakai  memposisikan...
1   harusnya jokowi lanjut tapi karna iuu membatas...
2                                            anis nol
3   knapa nis lo takut kalah krna gk di dukung pak...
4         ngakak         kmi rakyt tdk pernah di i...
5      menurut saya sih gak ada intervensi  lebay deh
6         rakyat  sudah tahu mana    bagus jadi  r...
7   jual gagasan saja jangan jual tuduhan  belar l...
8   saatnya orang keturunan yaman seperti pak anie...
9   anies boneka amrik  tak rela indonesia maju  m...
10  saya tdk merasa diintervensi negara  mau negar...
11  anies mimpi jadi presiden indonesia   tapi leb...
12                                      mulut mu anis
13  rakyat gk bodoh quot amat   hd rakyat sdh tau ...
14            betul omongan  pak anis tapi kerja omdo
15  mendidik rakyat lebih penting bung  biar gk salah
16  koar quot  presiden ikut cpur malah lebih baha...
17  inilah ciri orang takut kalah udah di gebar ge...
18  sejak dulu klompok pks dan kadrun jejak digita...
19               belom aja maju udah panik duluan wkw
20                                     bnyk cebong   
21   klo gk ikut campur di senayan wktu itu ngapain  
22  rakyat sdh cerdas dn berdaulat unt memilih pem...
23  saya yakin yg nda dukung anis baswedan yang ca...
24                 tp bgmn kl negara mmbantu anis    
25  bener pak jokowi harusnya melihat pendahulunya...
26  anies baswedan ngomong apa sih kamu melecehkan...
27  dasarnya munafik sudah terlihat kau bersikap s...
28  ga perlu cari orang yg tdk cakap utk bekerja y...
29                           katakan tidak untuk anis
30                cuma  makekar  capres     mukidi   
31  urus ssja ngara knaoa ikut cmpur btul rkyt pun...
32  bohog terus kapan ya gk bohong  pada takut kal...
33  ingat jakarta   thn terakhir      br cukup jak...
34  baguslah pintar berkata kata yg tujuannya baik...
35       cocok jadi tukang jual jamu  pinter ngomong 
36         klo soal pidato kayak gini mah jagonya dia
37  anid lucu siapa yg interpensi goblok  amat yg ...
38  anies udah jelas  survei nya rendah ketakutan ...
39      survey mana  cb cari survey di youtube    ...
40  pada takut jokowi karena pengaruhnya besar pem...
41                                   ke balik kali   
42         di intervensi mayatnya ga di sholatkan    
43  inilah congor anis yg slalu suudzon dengan sia...
44  rakyat dah pinter klo yg ngerti dukung yg bena...
45  siapa yg interpensi        gk ada aku  gk mili...
46  kompastv sdh condong ke anies  alias tdk netra...
47  semogah pak anis sehat selalu senantiasa dalam...
48  sempak si bewok suruh jadi presiden     yang b...
49  iya rakyat dah mampu menilai mana yg cuma pand...
50                                         wan ngibul
51  ketakutan kalah     belum aja pemilu udah keok...
52                  takut elektabilitas jokowi ya nis

**Slank Word**

In [15]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [16]:
!pip install indoNLP

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.9/121.9 kB 3.9 MB/s eta 0:00:00


In [ ]:
https://github.com/SalmatulFarida/prosaindata/blob/main/slankword.txt

In [18]:
slang_dict = pd.read_csv("https://raw.githubusercontent.com/SalmatulFarida/prosaindata/main/slankword.txt", sep=" ", header=None)
from indoNLP.preprocessing import replace_slang
from indoNLP.preprocessing import replace_word_elongation
replace_slang
def replace_slang_words(text):
    words = nltk.word_tokenize(text.lower())
    words_filtered = [word for word in words if word not in stopwords.words('indonesian')]
    for i in range(len(words_filtered)):
        if words_filtered[i] in slang_dict:
            words_filtered[i] = slang_dict[words_filtered[i]]
    return ' '.join(words_filtered)

# penggunaan
dt_lowecase=[]
for i in range(len(dt_clean)):
  dt_lowecase.append(dt_clean[i])

slang_words=[]
for i in range(len(dt_lowecase)):
  slang = replace_slang_words(dt_lowecase[i])
  y=replace_slang(slang)
  slang_words.append(y)

slang = pd.DataFrame(slang_words, columns=["data"])
slang

data
0   halah ilmunya beye pakai memposisikan orang te...
1        jokowi karena iuu membatasi ganjar solusinya
2                                            anis nol
3   knapa nis lo takut kalah karena enggak dukung ...
4   mengakak kami rakyt tidak intervensi negara pe...
5                     sih enggak intervensi lebay deh
6   rakyat bagus ri anis jakarta bobrok kok ri anc...
7   jual gagasan jual tuduhan belar kinerja jualan...
8   orang keturunan yaman anies presiden indonesia...
9   anies boneka amrik rela indonesia maju mulutny...
10  tidak diintervensi negara negara intervensi ya...
11  anies mimpi presiden indonesia cocok presiden ...
12                                      mulut mu anis
13  rakyat enggak bodoh quot hd rakyat sudah tau e...
14                     omongan anis kerja omong doang
15                  mendidik rakyat biar enggak salah
16  koar quot presiden cpur bahaya negara campur a...
17  ciri orang takut kalah sudah gebar gembilorkan...
18  klompok pks kadrun jejak digital pilgub sudah ...
19             belum saja maju sudah panik duluan wkw
20                                      banyak cebong
21          kalo enggak campur senayan waktu mengapai
22  rakyat sudah cerdas dan berdaulat unt memilih ...
23  yang indak dukung anis baswedan caci maki anis...
24            tapi bagaimana kalo negara mmbantu anis
25  benar jokowi pendahulunya belajar bagaimana me...
26  anies baswedan mengomong sih melecehkan ya pil...
27       dasarnya munafik kau bersikap enggak mengaku
28  enggak cari orang yang tidak cakap untuk yang ...
29                                               anis
30                              makekar capres mukidi
31  urus ssja ngara knaoa campur betul rkyt punys ...
32  bohog ya enggak bohong takut kalau pakai anis ...
33  jakarta tahun baru jakarta bohongi indonesia b...
34  baguslah pintar yang tujuannya ketimbang pinta...
35            cocok tukang jual jamu pintar mengomong
36               kalo pidato kayak begini mah jagonya
37  anid lucu yang interpensi goblok yang piluh ra...
38  anies sudah survei nya rendah ketakutan menyal...
39  survey coba cari survey youtube prov hasil men...
40  takut jokowi pengaruhnya pemilu maju bp jokowi...
41                                               kali
42               intervensi mayatnya enggak sholatkan
43  congor anis yang selalu suudzon yang enggak se...
44  rakyat deh pintar kalo yang mengerti dukung ya...
45  yang interpensi enggak enggak memilih yang pro...
46  kompastv sudah condong anies alias tidak netra...
47  semogah anis sehat senantiasa lindungan allah ...
48  sempak sih bewok suruh presiden benar saja pre...
49  iya rakyat deh menilai yang pandai tapi tak kr...
50                                         wan ngibul
51  ketakutan kalah saja pemilu sudah keok duluan ...
52                  takut elektabilitas jokowi ya nis

In [19]:
tokenize=[]
for i in range(len(slang_words)):
  token=word_tokenize(slang_words[i])
  tokendata = []
  for x in token :
    tokendata.append(x)
  tokenize.append(tokendata)
  print(tokendata)

['halah', 'ilmunya', 'beye', 'pakai', 'memposisikan', 'orang', 'teraniaya', 'terzolimi', 'nis', 'nis', 'cerdas', 'dikit', 'mencari', 'simpati', 'publik']
['jokowi', 'karena', 'iuu', 'membatasi', 'ganjar', 'solusinya']
['anis', 'nol']
['knapa', 'nis', 'lo', 'takut', 'kalah', 'karena', 'enggak', 'dukung', 'jokowi', 'baru', 'gue', 'enggak', 'negara', 'jatuh', 'tangan', 'aseng', 'kayak', 'lo']
['mengakak', 'kami', 'rakyt', 'tidak', 'intervensi', 'negara', 'pemerinth', 'selama', 'sudah', 'berapa', 'kali', 'ganti', 'presiden', 'baru', 'ngong', 'kayak', 'begitu']
['sih', 'enggak', 'intervensi', 'lebay', 'deh']
['rakyat', 'bagus', 'ri', 'anis', 'jakarta', 'bobrok', 'kok', 'ri', 'ancor', 'nkri']
['jual', 'gagasan', 'jual', 'tuduhan', 'belar', 'kinerja', 'jualan', 'bermain']
['orang', 'keturunan', 'yaman', 'anies', 'presiden', 'indonesia', 'baru', 'tenggelamkan', 'pemimpin', 'pribumi', 'baru', 'orang', 'cerdas', 'pilih', 'orang', 'yaman']
['anies', 'boneka', 'amrik', 'rela', 'indonesia', 'maju',

In [20]:
stopword=[]
for i in range(len(tokenize)):
  listStopword =  set(stopwords.words('indonesian'))
  removed=[]
  for x in (tokenize[i]):
    if x not in listStopword:
       removed.append(x)
  stopword.append(removed)
  print(removed)

['halah', 'ilmunya', 'beye', 'pakai', 'memposisikan', 'orang', 'teraniaya', 'terzolimi', 'nis', 'nis', 'cerdas', 'dikit', 'mencari', 'simpati', 'publik']
['jokowi', 'iuu', 'membatasi', 'ganjar', 'solusinya']
['anis', 'nol']
['knapa', 'nis', 'lo', 'takut', 'kalah', 'dukung', 'jokowi', 'gue', 'negara', 'jatuh', 'tangan', 'aseng', 'kayak', 'lo']
['mengakak', 'rakyt', 'intervensi', 'negara', 'pemerinth', 'kali', 'ganti', 'presiden', 'ngong', 'kayak']
['sih', 'intervensi', 'lebay', 'deh']
['rakyat', 'bagus', 'ri', 'anis', 'jakarta', 'bobrok', 'ri', 'ancor', 'nkri']
['jual', 'gagasan', 'jual', 'tuduhan', 'belar', 'kinerja', 'jualan', 'bermain']
['orang', 'keturunan', 'yaman', 'anies', 'presiden', 'indonesia', 'tenggelamkan', 'pemimpin', 'pribumi', 'orang', 'cerdas', 'pilih', 'orang', 'yaman']
['anies', 'boneka', 'amrik', 'rela', 'indonesia', 'maju', 'mulutnya', 'ember', 'bangga', 'bangsa', 'indonesia']
['diintervensi', 'negara', 'negara', 'intervensi', 'menentukan', 'ruang', 'bilik', 'percay

In [21]:
stemming=[]
for i in range(len(stopword)):
  factory = StemmerFactory()
  stemmer = factory.create_stemmer()
  katastem=[]
  for x in (stopword[i]):
    katastem.append(stemmer.stem(x))
  stemming.append(katastem)
  print(katastem)

['halah', 'ilmu', 'beye', 'pakai', 'posisi', 'orang', 'aniaya', 'terzolimi', 'nis', 'nis', 'cerdas', 'dikit', 'cari', 'simpati', 'publik']
['jokowi', 'iuu', 'batas', 'ganjar', 'solusi']
['anis', 'nol']
['knapa', 'nis', 'lo', 'takut', 'kalah', 'dukung', 'jokowi', 'gue', 'negara', 'jatuh', 'tangan', 'aseng', 'kayak', 'lo']
['akak', 'rakyt', 'intervensi', 'negara', 'pemerinth', 'kali', 'ganti', 'presiden', 'ngong', 'kayak']
['sih', 'intervensi', 'lebay', 'deh']
['rakyat', 'bagus', 'ri', 'anis', 'jakarta', 'bobrok', 'ri', 'ancor', 'nkri']
['jual', 'gagas', 'jual', 'tuduh', 'belar', 'kerja', 'jual', 'main']
['orang', 'turun', 'yaman', 'anies', 'presiden', 'indonesia', 'tenggelam', 'pimpin', 'pribumi', 'orang', 'cerdas', 'pilih', 'orang', 'yaman']
['anies', 'boneka', 'amrik', 'rela', 'indonesia', 'maju', 'mulut', 'ember', 'bangga', 'bangsa', 'indonesia']
['intervensi', 'negara', 'negara', 'intervensi', 'tentu', 'ruang', 'bilik', 'percaya', 'bawa', 'indonesia', 'arah', 'pilih', 'milu', 'luber

In [22]:
join=[]
for i in range(len(stemming)):
  joinkata = ' '.join(stemming[i])
  join.append(joinkata)

hasilpreproses = pd.DataFrame(join, columns=['data'])
hasilpreproses

data
0   halah ilmu beye pakai posisi orang aniaya terz...
1                      jokowi iuu batas ganjar solusi
2                                            anis nol
3   knapa nis lo takut kalah dukung jokowi gue neg...
4   akak rakyt intervensi negara pemerinth kali ga...
5                            sih intervensi lebay deh
6   rakyat bagus ri anis jakarta bobrok ri ancor nkri
7         jual gagas jual tuduh belar kerja jual main
8   orang turun yaman anies presiden indonesia ten...
9   anies boneka amrik rela indonesia maju mulut e...
10  intervensi negara negara intervensi tentu ruan...
11  anies mimpi presiden indonesia cocok presiden ...
12                                      mulut mu anis
13  rakyat bodoh quot hd rakyat tau intervensi lo ...
14                       omong anis kerja omong doang
15                            didik rakyat biar salah
16  koar quot presiden cpur bahaya negara campur a...
17  ciri orang takut kalah gebar gembilorkan kalah...
18  klompok pks kadrun jejak digital pilgub jls ho...
19                              maju panik duluan wkw
20                                             cebong
21                          kalo campur senayan kapai
22  rakyat cerdas daulat unt pilih pimpin bumi nus...
23  indak dukung anis baswedan caci maki anis basw...
24                           kalo negara mmbantu anis
25            jokowi dahulu ajar terus indonesia maju
26  anies baswedan omong sih leceh ya pilih capres...
27                        dasar munafik kau sikap aku
28  cari orang cakap kendali wni hak pilih pilih j...
29                                               anis
30                              makekar capres mukidi
31  urus ssja ngara knaoa campur rkyt punys hak mn...
32  bohog ya bohong takut pakai anis presiden hhhh...
33            jakarta jakarta bohong indonesia bohong
34  bagus pintar tuju ketimbang pintar bohong teru...
35                cocok tukang jual jamu pintar omong
36                         kalo pidato kayak mah jago
37  anid lucu interpensi goblok piluh rakyat ngaru...
38  anies survei nya rendah takut salah perintah a...
39  survey coba cari survey youtube prov hasil cen...
40    takut jokowi pengaruh milu maju bp jokowi hebat
41                                               kali
42                         intervensi mayat sholatkan
43  congor anis suudzon jalan denganya teman juang...
44  rakyat deh pintar kalo erti dukung quot pro ra...
45  interpensi pilih propokator belaka ada tuh isl...
46  kompastv condong anies alias netral orang muak...
47  semogah anis sehat senantiasa lindung allah sw...
48      sempak sih bewok suruh presiden prett kampret
49             iya rakyat deh nilai pandai krja kerja
50                                         wan ngibul
51  takut kalah milu keok duluan capres sayur jong...
52                  takut elektabilitas jokowi ya nis

**TF-IDF**

In [23]:
tr_model  = TfidfVectorizer()
tf_vector = tr_model.fit_transform(hasilpreproses['data'])

In [24]:
tf_array = tf_vector.toarray()
print(tf_array)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.43635367 0.         0.        ]]


In [25]:
words_set = tr_model.get_feature_names_out()
print(words_set)

['ada' 'agama' 'ahok' 'ajar' 'akak' 'akhlak' 'aku' 'alias' 'allah'
 'ambisi' 'amerika' 'amin' 'amrik' 'ancor' 'aniaya' 'anid' 'anies' 'anis'
 'arah' 'aseng' 'asli' 'bagus' 'bahaya' 'bangga' 'bangsa' 'banyak'
 'baswedan' 'batas' 'bawa' 'belaka' 'belar' 'bewok' 'beye' 'bgm' 'biar'
 'bilik' 'bobrok' 'bodoh' 'bohog' 'bohong' 'boneka' 'bp' 'bro' 'buang'
 'buka' 'bumi' 'caci' 'cakap' 'campur' 'capres' 'cari' 'cawapres' 'cawe'
 'cebong' 'cengang' 'cerdas' 'ciri' 'clon' 'coba' 'cocok' 'condong'
 'congor' 'cpur' 'cuman' 'curang' 'dahulu' 'dam' 'dapat' 'dasar' 'daulat'
 'deh' 'denganya' 'depan' 'depwn' 'didik' 'digital' 'dikit' 'dki' 'doang'
 'dukung' 'duluan' 'ekonomi' 'elektabilitas' 'ember' 'erti' 'fitnah'
 'gagas' 'ganjar' 'ganti' 'gebar' 'gembilorkan' 'goblok' 'gubernur' 'gue'
 'hak' 'halah' 'haram' 'harta' 'hasil' 'hd' 'hebat' 'hhhh' 'hoax' 'hsncur'
 'ilmu' 'imigran' 'indak' 'indonesia' 'inggris' 'interpensi' 'intervensi'
 'intetpensi' 'islam' 'islammmm' 'iuu' 'iya' 'jago' 'jakarta' 'jalan

In [26]:
df = pd.DataFrame(tf_array, columns = words_set)
df

ada     agama      ahok      ajar      akak    akhlak       aku  \
0   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4   0.000000  0.000000  0.000000  0.000000  0.353868  0.000000  0.000000   
5   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
6   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
9   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
10  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
11  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
12  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
13  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
14  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
15  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
16  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
17  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
18  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
19  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
20  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
21  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
22  0.000000  0.000000  0.000000  0.299537  0.000000  0.000000  0.000000   
23  0.000000  0.149822  0.000000  0.149822  0.000000  0.000000  0.000000   
24  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
25  0.000000  0.000000  0.000000  0.411427  0.000000  0.000000  0.000000   
26  0.000000  0.246644  0.000000  0.000000  0.000000  0.000000  0.000000   
27  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.412490   
28  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
29  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
30  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
31  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
32  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
33  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
34  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.245215   
35  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
36  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
37  0.000000  0.000000  0.187289  0.000000  0.000000  0.187289  0.000000   
38  0.000000  0.259699  0.000000  0.000000  0.000000  0.000000  0.000000   
39  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
40  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
41  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
42  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
43  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
44  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
45  0.352178  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
46  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
47  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
48  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
49  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
50  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
51  0.000000  0.000000  0.000000  0.000000  0.000000  0.0

Singular Value Decomposition

teknik untuk mendekomposisi matriks berukuran apa saja (biasanya diaplikasikan untuk matriks dengan ukuran sangat besar), untuk mempermudah pengolahan data

In [27]:
from sklearn.decomposition import TruncatedSVD
lsa_model = TruncatedSVD(n_components=3, algorithm='randomized', n_iter=10, random_state=42)
lsa_top=lsa_model.fit_transform(df)

In [28]:
print(lsa_top)
print(lsa_top.shape)  # (no_of_doc*no_of_topics)

[[ 1.40799920e-01 -1.03971590e-01  1.92546274e-01]
 [ 5.00821828e-02 -1.02941876e-01  2.81044099e-01]
 [ 3.65525377e-01  4.86832224e-01  5.83631847e-02]
 [ 2.25991815e-01 -1.82009509e-01  3.32465933e-01]
 [ 2.10233518e-01 -1.21794864e-01 -1.14701437e-01]
 [ 1.53596469e-01 -1.94344508e-01 -2.52702070e-01]
 [ 2.51552901e-01  1.08854873e-01 -8.78203942e-02]
 [ 9.61389284e-02 -7.64297778e-02 -4.48663704e-02]
 [ 3.40699868e-01 -3.31795291e-01 -1.04072226e-02]
 [ 2.02278712e-01 -1.47706065e-01  1.96734120e-01]
 [ 2.76453909e-01 -1.80650869e-01 -7.60193486e-02]
 [ 4.51239317e-01 -3.92575965e-01 -1.61387060e-01]
 [ 3.52069924e-01  4.15912195e-01  8.08573771e-02]
 [ 3.39251950e-01 -3.28049964e-01 -3.22660757e-01]
 [ 3.51732949e-01  1.66098886e-01 -6.61051302e-02]
 [ 1.51640110e-01 -1.54936612e-01 -1.85980913e-01]
 [ 3.84983540e-01  2.20818401e-02 -1.61862844e-01]
 [ 1.14859132e-01 -1.50907161e-01  2.32840586e-01]
 [ 3.38010362e-02  4.97715658e-03  4.02738655e-02]
 [ 4.90749356e-02 -9.93400644e-

In [29]:
#bobot setiap topik terhadap dokumen
dt = pd.DataFrame(lsa_top, columns=['topik1','topik2','topik3'])
dt

topik1    topik2    topik3
0   0.140800 -0.103972  0.192546
1   0.050082 -0.102942  0.281044
2   0.365525  0.486832  0.058363
3   0.225992 -0.182010  0.332466
4   0.210234 -0.121795 -0.114701
5   0.153596 -0.194345 -0.252702
6   0.251553  0.108855 -0.087820
7   0.096139 -0.076430 -0.044866
8   0.340700 -0.331795 -0.010407
9   0.202279 -0.147706  0.196734
10  0.276454 -0.180651 -0.076019
11  0.451239 -0.392576 -0.161387
12  0.352070  0.415912  0.080857
13  0.339252 -0.328050 -0.322661
14  0.351733  0.166099 -0.066105
15  0.151640 -0.154937 -0.185981
16  0.384984  0.022082 -0.161863
17  0.114859 -0.150907  0.232841
18  0.033801  0.004977  0.040274
19  0.049075 -0.099340  0.213882
20 -0.000009  0.000281 -0.000161
21  0.124727  0.027795 -0.084569
22  0.208652 -0.186982 -0.095450
23  0.305630  0.112776  0.035538
24  0.441646  0.337889 -0.039834
25  0.177190 -0.245093  0.406234
26  0.230337 -0.188438 -0.002649
27  0.005456 -0.007958 -0.003163
28  0.202116 -0.105009 -0.002810
29  0.544939  0.643279  0.072713
30  0.059459 -0.090700 -0.008086
31  0.023597 -0.004792 -0.014998
32  0.391981  0.098085  0.172105
33  0.130361 -0.062177  0.048343
34  0.098787 -0.094073 -0.029187
35  0.178976 -0.130731 -0.110867
36  0.131159 -0.023929 -0.058406
37  0.383025  0.168588 -0.040009
38  0.152257 -0.177587  0.088444
39  0.010966 -0.010543  0.012391
40  0.139721 -0.236827  0.561001
41  0.036686 -0.033702 -0.038755
42  0.094711 -0.123352 -0.156295
43  0.180874  0.080629  0.249012
44  0.358144 -0.276161 -0.409036
45  0.078418 -0.027723 -0.027329
46  0.086194 -0.108056  0.027439
47  0.187948  0.249064  0.041907
48  0.098000 -0.087400 -0.063303
49  0.179749 -0.138821 -0.255468
50 -0.000005 -0.000072 -0.000105
51  0.128145 -0.177510  0.274299
52  0.174265 -0.194358  0.571363

In [30]:
V = lsa_model.components_
print(V)
print(V.shape) # (no_of_topics*no_of_words)

[[ 9.73368156e-03  5.01068144e-02  2.52845799e-02  6.38691930e-02
   2.62226043e-02  2.52845799e-02  9.33521165e-03  9.62724719e-03
   5.06637904e-02  1.54382342e-02  4.16596623e-02  2.47970923e-02
   2.32360553e-02  2.89965049e-02  1.32809897e-02  2.52845799e-02
   1.13274170e-01  5.44938921e-01  2.78433838e-02  2.29797881e-02
   3.69370517e-02  3.47971277e-02  4.16596623e-02  2.32360553e-02
   2.32360553e-02  1.92453526e-02  5.64834495e-02  8.27242902e-03
   2.78433838e-02  9.73368156e-03  1.06171599e-02  1.38681795e-02
   1.32809897e-02  2.52845799e-02  2.98309158e-02  2.78433838e-02
   2.89965049e-02  3.31085850e-02  3.11470160e-02  6.41325128e-02
   3.75518028e-02  1.86199412e-02  2.62704127e-02  1.54382342e-02
   1.54382342e-02  2.62704127e-02  3.84907051e-02  1.82294983e-02
   6.80217558e-02  9.24243751e-02  2.74629862e-02  2.38796028e-02
   1.88545480e-02 -9.37870766e-06  1.23629804e-03  8.98360071e-02
   1.36986585e-02  1.89022773e-03  1.23629804e-03  5.98645314e-02
   9.62724

In [39]:
#bobot setiap kata terhadap topik
label=[]
for i in range (1,291):
  masukan = f"kata ke-{i}"
  label.append(masukan)
V = pd.DataFrame(V,columns=label)
V.rename(index={0:"Topik 1",1:"Topik 2",2:"Topik 3",3:"Topik 4",4:"Topik 5",5:"Topik 6"})

kata ke-1  kata ke-2  kata ke-3  kata ke-4  kata ke-5  kata ke-6  \
Topik 1   0.009734   0.050107   0.025285   0.063869   0.026223   0.025285   
Topik 2  -0.004528  -0.035044   0.014588  -0.064700  -0.019938   0.014588   
Topik 3  -0.004950   0.014044  -0.003834   0.073457  -0.020754  -0.003834   

         kata ke-7  kata ke-8  kata ke-9  kata ke-10  ...  kata ke-281  \
Topik 1   0.009335   0.009627   0.050664    0.015438  ...     0.003780   
Topik 2  -0.012117  -0.015861   0.048304    0.009051  ...    -0.000995   
Topik 3  -0.004316   0.004431   0.025207    0.030829  ...    -0.003585   

         kata ke-282  kata ke-283  kata ke-284  kata ke-285  kata ke-286  \
Topik 1     0.031147     0.018229    -0.000004     0.018229     0.009329   
Topik 2     0.010218    -0.012405    -0.000051    -0.012405    -0.024691   
Topik 3     0.019816    -0.000371    -0.000074    -0.000371     0.058917   

         kata ke-287  kata ke-288  kata ke-289  kata ke-290  
Topik 1     0.018229     0.082238     0.126639     0.001236  
Topik 2    -0.012405    -0.044219    -0.152648    -0.001555  
Topik 3    -0.000371     0.166916    -0.037281     0.002094  

[3 rows x 290 columns]